#!/bin/sh

# Mount the drives, if not already mounted
BackupMounted=$(mount | grep -c /mnt/backup)

echo "## RSNAPSHOT PROCESSING"

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }

if [ $BackupMounted -eq 0 ]
then
    try mount /mnt/backup
    echo "Backup drive mounted"
else
    echo "Backup drive already mounted"
fi

# If no daily backup file or it is older than yesterday, then do daily backup
if [ -f /mnt/backup/daily.0 ]; 
then
    LastDailyDate=$(date -r /mnt/backup/daily.0 +%s)
    YesterdayDate=$(date -d "yesterday" +%s)
    if [ $YesterdayDate -gt $LastDailyDate ]
    then 
         DoDailyBackup=1
         echo "Daily backup required"
     else
         DoDailyBackup=0
    fi
else 
    DoDailyBackup=1
fi

if [[ -f /mnt/backup/weekly.0 ]]
then 
    LastWeeklyDate=$(date -r /mnt/backup/weekly.0 +%s)
    LastWeekDate=$(date -d "last week" +%s)
    if [[ $LastWeekDate -gt $LastWeeklyDate ]]
    then
        DoWeeklyBackup=1
    else
        DoWeeklyBackup=0
    fi
else
    DoWeeklyBackup=1
fi

if [ -f /mnt/backup/monthly.0 ]
then
    LastMonthlyDate=$(date -r /mnt/backup/monthly.0 +%s)
    LastMonthDate=$(date -d "last month" +%s)
    if [ $LastMonthDate -gt $LastMonthlyDate ]
    then 
        DoMonthlyBackup=1
    else
        DoMonthlyBackup=0
    fi
else # file doesn't exist
    DoMonthlyBackup=1
fi


if [[ $DoDailyBackup -eq 1 ]]
then
	echo "### RSNAPSHOT DAILY ###"
	echo "Running daily backup process"
	rsnapshot -c /etc/rsnapshot.d/daily.conf daily || echo "Backup failure"
	echo
else
	echo "Daily backup < 1 day old - not running again"
fi


if [[ $DoWeeklyBackup -eq 1 ]]
then
	echo "### RSNAPSHOT WEEKLY ###"
	echo "Running weekly backup process"
	rsnapshot -c /etc/rsnapshot.d/weekly.conf weekly || echo "Backup failure"
	echo
else
	echo "Weekly backup < 1 week old - not running again"
fi

if [[ $DoMonthlyBackup -eq 1 ]]
then
	echo "### RSNAPSHOT MONTHLY ###"
	echo "Running monthly backup process"
	rsnapshot -c /etc/rsnapshot.d/monthly.conf monthly || echo "Backup failure"
	echo
else
	echo "Monthly backup < 1 month old - not running again"
fi

if [[ !$BackupMounted -eq 1 ]]
then
	umount /mnt/backup
	echo "Backup drive unmounted"
else
	echo "Backup drive was already mounted so not unmounted"
fi

echo "## RSNAPSHOT PROCESS COMPLETED ##"
